#!/bin/bash

usage() {
	echo "Correct usage: $0 [-n <num of days>] [-m '*.extension'] [-a <yourtarname.tar>]"; 
	exit 1;
}

while getopts ":n:m:a:" o; do
	case "${o}" in
		n)
			n=${OPTARG}
			re='^[0-9]+$'
			if ! [[ $n =~ $re ]]; then
				echo -e "BAD DAY NUMBER FORMAT!\n"
				usage;
			fi
			;;
		m)
			m=${OPTARG}
			if [[ $m != "."* ]]; then
				echo -e "BAD EXTENSION FORMAT!\n"
				usage;
			fi
			;;
		a)
			a=${OPTARG}
			if [[ $a != *".tar" ]]; then
				echo -e "BAD TAR FORMAT!\n"
				usage;
			fi
			;;
	esac
done

shift $((OPTIND-1))
if [ -z "${n}" ]; then
	echo "Enter number of days!: ";
	read -r line;
	n="$line";
	re='^[0-9]+$'
	if ! [[ $n =~ $re ]]; then
		echo -e "BAD DAY NUMBER FORMAT!\n"
		usage;
	fi
fi

if [ -z "${m}" ]; then
	echo "Enter extension!: ";
	read -r line;
	m="$line";
	if [[ $m != "."* ]]; then
		echo -e "BAD EXTENSION FORMAT!\n"
		usage;
	fi
fi

if [ -z "${a}" ]; then
	echo "Enter tar name!: ";
	read -r line;
	a="$line";
	if [[ $a != *".tar" ]]; then
		echo -e "BAD TAR FORMAT!\n"
		usage;
	fi
fi

OUTPUT="$(find *${m} -mtime -${n})"
i=0;
while read -r line
do
	filename[i]="$line";
	let "i=i+1";
done <<< "${OUTPUT}"
tar -c -f ${a} "${filename[0]}"
for (( i=1; i<"${#filename[*]}"; i++ ))
do
	tar -rvf ${a} "${filename[i]}"
done

echo "${n} ${m} ${a}"